project:
  type: website
  output-dir: docs

website:
  title: "ExeDataHub"
  site-url: https://exeter-data-analytics.github.io/
  repo-url: https://github.com/exeter-data-analytics/exeter-data-analytics.github.io
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: series.qmd
        text: Series
      - href: presentations.qmd
        text: Presentations
      - href: posts.qmd
        text: Walkthroughs
      - icon: github
        href: https://github.com/exeter-data-analytics/exeter-data-analytics.github.io

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    
comments:
  giscus:
    repo: exeter-data-analytics/exeter-data-analytics.github.io

editor: visual

