project:
  type: website
  output-dir: docs

website:
  title: "ExeDataHub"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true

editor: visual

