---
title: "intRos: Walkthroughs"
comments: false
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  feed: true
  fields: [title, description, date, reading-time]
  date-format: "YYYY-MM-DD"
  page-size: 9
---

## What is the intRos series?

The intRos walkthrough series is designed to be a place to provide brief introductions and walkthroughs for activities that are common when programming for research purposes. For example, using **ggplot2** and making publication-ready plots. Or making reproducible tables in R using **flextable**. These intRos are aimed to be brief and designed to get you started using these tools. Throughout we highlight where we find information and our favourite resources for when we get stuck!

We hope that this series will be added to through time by other members of the University.

## Get started

All of the available intRos can be found below. All of the reproducible quarto (.qmd) files can be found at the source [GitHub](https://github.com/exeter-data-analytics/exeter-data-analytics.github.io) repository for this website. You can navigate to each of the directories individually in the `posts/` folder, or better still clone the repo using `git clone` and open the project in RStudio. 

***